config/routes.rb
Rails.application.routes.draw do
  resources :events
  root :to => 'events#index'
  devise_for :users
  resources :users, :only => :show
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    after_create :new_attendance

    belongs_to :user
    belongs_to :event

    def new_attendance
        AttendanceMailer.participate_event(self).deliver_now
    end
end

app/models/event.rb
class Event < ApplicationRecord


    has_many :users
    belongs_to :admin, class_name: "User"
    validates :start_date, presence: true 
    validate :event_validation

    validates :duration, presence: true
    validate :duration_x5_positif
    validates :title, presence: true, length: { in: 5..140 }
    validates :description, presence: true, length: { in: 20..1000 }

    validates :price, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
    
    validates :location, presence: true

    def event_validation
       if start_date.to_i < DateTime.now.to_i
        errors.add(:start_date, "la date est dépassée")
       end
    end
    
    def duration_x5_positif
        if (duration.to_i % 5 != 0 || duration.to_i < 0)
        errors.add(:duration, "la durée doit être un multiple de 5 et positif ")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send
    
    has_many :events, foreign_key: 'admin_id', class_name: "Event"
    has_many :events
    has_many :events, through: :attendance
    
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  attr_accessor :events

  def index
  end

  def new
    @event = Event.new 
  end


  def show
  end

  def create
    puts "________________________________________"
    puts current_user.id
    puts params[:start_date]

    @event = Event.new('admin_id' => current_user.id,
    'title' => params[:title],
    'start_date' => params[:start_date],
    'duration' => params[:duration],
    'price' => params[:price],
    'location' => params[:location],
    'description' => params[:description])
    
      @event.save
  if @event.save
    flash[:success] = "Gossip Created Successfully"
    redirect_to root_path #changer le path

    else
render 'new'
    end
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]

	before_action :access_profile?, only: [:show]

  def show
  	@user = User.find(params[:id])
  	
  end

  def access_profile?
  	if current_user.id != params[:id].to_i
   		redirect_to root_path, :alert => "Restricted area" 
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

def event_helper
	@event = Event.all
end

def new_event
	Event.new
end

def event_current
	Event.find_by(id: params[:id])
end

def admin_event_email
	User.find(event_current.admin_id).email
end

end

app/helpers/users_helper.rb
module UsersHelper

def user_event_created
	Event.find_by(admin_id: @user)
end


end

app/views/events/index.html.erb
<h1>Events of your city</h1>
<p>

	<% event_helper.each do |event| %>
<div class="container">
<div class="card" style="width: 18rem;">
 <div class="card-body">
   <h5 class="card-title"><%= link_to event.title, event_path(event.id) %>
   <h6 class="card-subtitle mb-2 text-muted"><%= event.price %> balles</h6>
   <p class="card-text"><%=event.description%></p>
   <h6 class="card-subtitle mb-2 text-muted">City: <%= event.location %></h6>
 </div>
 </div>
</div><br>

	<% end %>

</p>

app/views/events/new.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-10">
      <h1 class="text-center mt-5"> Create your event ! </h1>
      <div class="d-flex justify-content-center">
        <br>
      </div> <br>
    </div>
    <br>

<div class="container card">
  <br>
 <%= form_tag url_for(action: "create"), method: "post" do %>
      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', new_event.title, class: 'form-control'%>
      <br /> <br />
       <%= label_tag 'Start_date' %>
      <%= text_field_tag 'start_date', new_event.start_date, class: 'form-control'%>
      <br /> <br />
       <%= label_tag 'Duration' %>
      <%= text_field_tag 'duration', new_event.duration, class: 'form-control'%>
      <br /> <br />
       <%= label_tag 'Price' %>
      <%= text_field_tag 'price', new_event.price, class: 'form-control'%>
      <br /> <br />
       <%= label_tag 'Location' %>
      <%= text_field_tag 'location', new_event.location, class: 'form-control'%>
      <br /> <br />

      <%= label_tag 'Description' %>
      <%= text_area_tag 'description', new_event.description, class: 'form-control'%>

      <br /> <br />

      <%= submit_tag "Create Event", class: 'btn btn-primary' %>
  <% end %>
  <br>
</div>

app/views/events/show.html.erb
<br><br>
<div class="card text-center m-5">
  <div class="card-header"><%= event_current.title %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Special Event</h5>
    <p class="card-text"><%= event_current.description %></p>
  </div>
  <div class="card-footer text-muted">The 
    <%= event_current.start_date.strftime("%a %b #{event_current.start_date.day.ordinalize}") %>    By: <%= admin_event_email %> In: <%= event_current.location %> <%= event_current.price %>€
  </div>
</div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<%= root_path %>"> EventBraite </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if current_user %>
            <a class="nav-item nav-link" href="<%= user_path(current_user.id) %>"> Profile <span class="sr-only">(current)</span></a>
          <% end %>
            <a class="nav-item nav-link" href="<%= new_event_path %>">New event</a>

        </div>
    </div>


	<div>
		<li><a class="btn btn-success p-3 pl-5 pr-5" href="<%= new_user_session_path%>" role="button">Login</a></li>

	</div>
	<div>
		<li><a class="btn btn-light p-3 pl-5 pr-5" href="<%=new_user_registration_path%>" role="button">Sign in</a></li>
	</div>

	<div>
		<li><%= link_to "Logout", destroy_user_session_path, :method => 'DELETE', class: "btn btn-primary p-3 pl-5 pr-5" %></li>
	</div>


</nav>	

<% if flash[:success] %>
  <div class= "alert alert-danger">
    <%= flash[:success] %>
      <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
    <%= render 'layouts/header' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<br><br>
<div class="card m-5">
  <h5 class="card-header"><%= @user.first_name %> <%= @user.last_name %></h5>

  <div class="card-body">
    <p class="card-text"><%= @user.description %></p>
    <p class="card-text"><%= @user.email %></p>
    <a class="btn btn-light p-3 pl-5 pr-5" href="<%=edit_user_registration_path%>" role="button">Edit</a>

   <!--  <a href="#" class="btn btn-primary">Go somewhere</a> -->
  </div>
</div>
<h3 class="text-center"> Event Created </h3>
<% Event.all.each do |event| %>
<% if event.admin_id == @user.id %>
	<div class="container">
	<div class="card" style="width: 18rem;">
	 <div class="card-body">
	   <h5 class="card-title"><%= event.title %></h5>
	   <h6 class="card-subtitle mb-2 text-muted"><%= event.price %> balles</h6>
	   <p class="card-text"><%=event.description%></p>
	   <h6 class="card-subtitle mb-2 text-muted">City: <%= event.location %></h6>
	 </div>
	 </div>
	</div><br>
	<% end %>
	<% end %>